name: dagger
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Functions
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          module: github.com/kpenfound/dagger-modules/golang@v0.2.0
          args: build-container --source=. --args=. publish --address=ttl.sh/my-app-$RANDOM
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Go test pipeline
        run: dagger run go run dagger/unit-test/main.go

      - name: Terraform pipeline
        run: dagger run go run dagger/tf-plan/main.go

      - name: Lint JSON with Dagger pipeline
        run: dagger run go run dagger/jsonlint/main.go
