name: dagger
on:
  push:
    branches: [main]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go test pipeline
        uses: dagger/dagger-for-github@v6
        with:
          verb: run
          args: go run dagger/unit-test/main.go

      - name: Terraform pipeline
        uses: dagger/dagger-for-github@v6
        with:
          verb: run
          args: go run dagger/tf-plan/main.go -tfImage=hashicorp/terraform:1.4.0"

      - name: Lint JSON with Dagger pipeline
        uses: dagger/dagger-for-github@v6
        with:
          verb: run
          args: go run dagger/jsonlint/main.go
