name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dagger-pipelines:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5"

      - name: Install Dagger CLI
        uses: dagger/engine-action@v3
        with:
          version: latest

      - name: Go test pipeline
        run: dagger run go run dagger/unit-test/main.go

      - name: Terraform pipeline
        run: dagger run go run dagger/tf-plan/main.go

      - name: Lint JSON with Dagger pipeline
        run: dagger run go run dagger/jsonlint/main.go
